name: Build

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Fastlane Action
      uses: maierj/fastlane-action@v1.0.0
      with:
        lane: scan_project
